修改分页标签指定了默认排序字段，但是默认排序字段与title标签指定的排序字段不同时，翻页时会抛出空指针异常
java.lang.NullPointerException

    at
com.frameworkset.common.tag.pager.tags.TitleTag.desc(TitleTag.java:263)

    at
com.frameworkset.common.tag.pager.tags.TitleTag.generateTHContent(TitleTag.java:420)

    at
com.frameworkset.common.tag.pager.tags.TitleTag.doStartTag(TitleTag.java:129)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspx_meth_pg_005ftitle_005f0(oopPaymentForGoodsListInfo_jsp.java:1380)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspx_meth_pg_005fheader_005f0(oopPaymentForGoodsListInfo_jsp.java:766)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspService(oopPaymentForGoodsListInfo_jsp.java:217)

    at
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)

    at
org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)

    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)

    at
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)

    at
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)

    at
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)

    at
org.frameworkset.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:216)

    at
org.frameworkset.web.servlet.view.AbstractView.render(AbstractView.java:248)

    at
org.frameworkset.web.servlet.DispatchServlet.render(DispatchServlet.java:1166)

    at
org.frameworkset.web.servlet.DispatchServlet.doDispatch(DispatchServlet.java:904)

    at
org.frameworkset.web.servlet.DispatchServlet.doService(DispatchServlet.java:714)

    at
org.frameworkset.web.servlet.DispatchServlet.processRequest(DispatchServlet.java:455)

    at
org.frameworkset.web.servlet.DispatchServlet.doPost(DispatchServlet.java:1845)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
com.sany.oop.filter.CheckUserPwdFilter.doFilter(CheckUserPwdFilter.java:47)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.frameworkset.web.interceptor.AuthenticateFilter.doFilter(AuthenticateFilter.java:607)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.frameworkset.security.session.impl.SessionFilter.doFilter(SessionFilter.java:60)

    at
com.frameworkset.common.filter.BaseCharsetEncodingFilter.doFilter(BaseCharsetEncodingFilter.java:133)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)

    at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)

    at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)

    at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)

    at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)

    at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)

    at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)

    at
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)

    at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)

    at
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)

    at java.lang.Thread.run(Unknown Source)

一月 07, 2016 9:49:21 上午 org.apache.catalina.core.ApplicationDispatcher
invoke

严重: Servlet.service() for servlet jsp threw exception

javax.servlet.jsp.JspException: Title tag must be set in header tag in
list or pager tag:null

    at
com.frameworkset.common.tag.pager.tags.TitleTag.doStartTag(TitleTag.java:155)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspx_meth_pg_005ftitle_005f0(oopPaymentForGoodsListInfo_jsp.java:1380)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspx_meth_pg_005fheader_005f0(oopPaymentForGoodsListInfo_jsp.java:766)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspService(oopPaymentForGoodsListInfo_jsp.java:217)

    at
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)

    at
org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)

    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)

    at
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)

    at
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)

    at
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)

    at
org.frameworkset.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:216)

    at
org.frameworkset.web.servlet.view.AbstractView.render(AbstractView.java:248)

    at
org.frameworkset.web.servlet.DispatchServlet.render(DispatchServlet.java:1166)

    at
org.frameworkset.web.servlet.DispatchServlet.doDispatch(DispatchServlet.java:904)

    at
org.frameworkset.web.servlet.DispatchServlet.doService(DispatchServlet.java:714)

    at
org.frameworkset.web.servlet.DispatchServlet.processRequest(DispatchServlet.java:455)

    at
org.frameworkset.web.servlet.DispatchServlet.doPost(DispatchServlet.java:1845)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
com.sany.oop.filter.CheckUserPwdFilter.doFilter(CheckUserPwdFilter.java:47)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.frameworkset.web.interceptor.AuthenticateFilter.doFilter(AuthenticateFilter.java:607)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.frameworkset.security.session.impl.SessionFilter.doFilter(SessionFilter.java:60)

    at
com.frameworkset.common.filter.BaseCharsetEncodingFilter.doFilter(BaseCharsetEncodingFilter.java:133)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)

    at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)

    at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)

    at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)

    at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)

    at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)

    at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)

    at
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)

    at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)

    at
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)

    at java.lang.Thread.run(Unknown Source)

 

org.apache.jasper.JasperException: javax.servlet.ServletException:
javax.servlet.jsp.JspException: Title tag must be set in header tag in
list or pager tag:null

    at
org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:502)

    at
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:412)

    at
org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)

    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)

    at
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)

    at
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)

    at
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)

    at
org.frameworkset.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:216)

    at
org.frameworkset.web.servlet.view.AbstractView.render(AbstractView.java:248)

    at
org.frameworkset.web.servlet.DispatchServlet.render(DispatchServlet.java:1166)

    at
org.frameworkset.web.servlet.DispatchServlet.doDispatch(DispatchServlet.java:904)

    at
org.frameworkset.web.servlet.DispatchServlet.doService(DispatchServlet.java:714)

    at
org.frameworkset.web.servlet.DispatchServlet.processRequest(DispatchServlet.java:455)

    at
org.frameworkset.web.servlet.DispatchServlet.doPost(DispatchServlet.java:1845)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
com.sany.oop.filter.CheckUserPwdFilter.doFilter(CheckUserPwdFilter.java:47)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.frameworkset.web.interceptor.AuthenticateFilter.doFilter(AuthenticateFilter.java:607)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.frameworkset.security.session.impl.SessionFilter.doFilter(SessionFilter.java:60)

    at
com.frameworkset.common.filter.BaseCharsetEncodingFilter.doFilter(BaseCharsetEncodingFilter.java:133)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)

    at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)

    at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

    at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)

    at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)

    at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)

    at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)

    at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)

    at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)

    at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)

    at
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)

    at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)

    at
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)

    at java.lang.Thread.run(Unknown Source)

Caused by: javax.servlet.ServletException:
javax.servlet.jsp.JspException: Title tag must be set in header tag in
list or pager tag:null

    at
org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:868)

    at
org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:797)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspService(oopPaymentForGoodsListInfo_jsp.java:460)

    at
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

    at
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)

    ... 44 more

Caused by: javax.servlet.jsp.JspException: Title tag must be set in
header tag in list or pager tag:null

    at
com.frameworkset.common.tag.pager.tags.TitleTag.doStartTag(TitleTag.java:155)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspx_meth_pg_005ftitle_005f0(oopPaymentForGoodsListInfo_jsp.java:1380)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspx_meth_pg_005fheader_005f0(oopPaymentForGoodsListInfo_jsp.java:766)

    at
org.apache.jsp.sanyoop.paymentForGoods.oopPaymentForGoodsListInfo_jsp._jspService(oopPaymentForGoodsListInfo_jsp.java:217)

    ... 47 more